"""create heritage site historical events table

Revision ID: 0584223d68ed
Revises: 5490979330d7
Create Date: 2026-08-09 18:44:24.711534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0584223d68ed'
down_revision: Union[str, Sequence[str], None] = '5490979330d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('heritage_site_historical_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('date_precision', sa.Enum('YEAR', 'MONTH', 'DAY', 'APPROXIMATE', 'PERIOD', 'UNKNOWN', name='dateprecision'), nullable=False),
    sa.Column('significance', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['heritage_sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_heritage_site_historical_events_date_precision'), 'heritage_site_historical_events', ['date_precision'], unique=False)
    op.create_index(op.f('ix_heritage_site_historical_events_site_id'), 'heritage_site_historical_events', ['site_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_heritage_site_historical_events_site_id'), table_name='heritage_site_historical_events')
    op.drop_index(op.f('ix_heritage_site_historical_events_date_precision'), table_name='heritage_site_historical_events')
    op.drop_table('heritage_site_historical_events')
    # ### end Alembic commands ###
