"""add historical event date label

Revision ID: 0e39da2af598
Revises: 0584223d68ed
Create Date: 2026-08-12 19:15:14.552532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e39da2af598'
down_revision: Union[str, Sequence[str], None] = '0584223d68ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('heritage_site_historical_events', sa.Column('date_label', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('heritage_site_historical_events', 'date_label')
    # ### end Alembic commands ###
