"""create scanner scans table

Revision ID: 1604f8627652
Revises: f515ceb60c1f
Create Date: 2026-08-15 15:20:55.556908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1604f8627652'
down_revision: Union[str, Sequence[str], None] = 'f515ceb60c1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('identification_status', sa.String(length=32), nullable=False),
    sa.Column('evidence_quality', sa.String(length=16), nullable=False),
    sa.Column('identified_name', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=128), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('confidence_level', sa.String(length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('architectural_style', sa.String(length=255), nullable=True),
    sa.Column('historical_period', sa.String(length=255), nullable=True),
    sa.Column('historical_significance', sa.Text(), nullable=True),
    sa.Column('visual_evidence', sa.JSON(), nullable=False),
    sa.Column('alternative_matches', sa.JSON(), nullable=False),
    sa.Column('grounding_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scans_user_id'), 'scans', ['user_id'], unique=False)
    op.create_index('ix_scans_user_id_created_at', 'scans', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scans_user_id_created_at', table_name='scans')
    op.drop_index(op.f('ix_scans_user_id'), table_name='scans')
    op.drop_table('scans')
    # ### end Alembic commands ###

