"""create heritage sites table

Revision ID: 1d106e696849
Revises: 6c2326aa3289
Create Date: 2026-08-09 11:34:34.095497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d106e696849'
down_revision: Union[str, Sequence[str], None] = '6c2326aa3289'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('heritage_sites',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('short_description', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('established_year', sa.Integer(), nullable=True),
    sa.Column('architectural_style', sa.String(length=150), nullable=True),
    sa.Column('historical_period', sa.String(length=150), nullable=True),
    sa.Column('significance', sa.Text(), nullable=True),
    sa.Column('preservation_status', sa.String(length=100), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_heritage_sites_category'), 'heritage_sites', ['category'], unique=False)
    op.create_index(op.f('ix_heritage_sites_city'), 'heritage_sites', ['city'], unique=False)
    op.create_index(op.f('ix_heritage_sites_name'), 'heritage_sites', ['name'], unique=False)
    op.create_index(op.f('ix_heritage_sites_slug'), 'heritage_sites', ['slug'], unique=True)
    op.create_index(op.f('ix_heritage_sites_state'), 'heritage_sites', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_heritage_sites_state'), table_name='heritage_sites')
    op.drop_index(op.f('ix_heritage_sites_slug'), table_name='heritage_sites')
    op.drop_index(op.f('ix_heritage_sites_name'), table_name='heritage_sites')
    op.drop_index(op.f('ix_heritage_sites_city'), table_name='heritage_sites')
    op.drop_index(op.f('ix_heritage_sites_category'), table_name='heritage_sites')
    op.drop_table('heritage_sites')
    # ### end Alembic commands ###
