"""create heritage site metadata table

Revision ID: 3d9f59bbafd3
Revises: 8210ab2b6bdc
Create Date: 2026-08-09 13:12:03.002441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d9f59bbafd3'
down_revision: Union[str, Sequence[str], None] = '8210ab2b6bdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('heritage_site_metadata',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('metadata_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=300), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['heritage_sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_heritage_site_metadata_language'), 'heritage_site_metadata', ['language'], unique=False)
    op.create_index(op.f('ix_heritage_site_metadata_metadata_type'), 'heritage_site_metadata', ['metadata_type'], unique=False)
    op.create_index(op.f('ix_heritage_site_metadata_site_id'), 'heritage_site_metadata', ['site_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_heritage_site_metadata_site_id'), table_name='heritage_site_metadata')
    op.drop_index(op.f('ix_heritage_site_metadata_metadata_type'), table_name='heritage_site_metadata')
    op.drop_index(op.f('ix_heritage_site_metadata_language'), table_name='heritage_site_metadata')
    op.drop_table('heritage_site_metadata')
    # ### end Alembic commands ###
