"""create heritage site relations table

Revision ID: 5490979330d7
Revises: 4162a907fa80
Create Date: 2026-08-09 17:25:42.783211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5490979330d7'
down_revision: Union[str, Sequence[str], None] = '4162a907fa80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('heritage_site_relations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_site_id', sa.String(length=36), nullable=False),
    sa.Column('target_site_id', sa.String(length=36), nullable=False),
    sa.Column('relation_type', sa.Enum('RELATED_TO', 'PART_OF', 'ASSOCIATED_WITH', 'LOCATED_NEAR', 'HISTORICALLY_CONNECTED', name='relationtype'), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_site_id'], ['heritage_sites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_site_id'], ['heritage_sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_heritage_site_relations_relation_type'), 'heritage_site_relations', ['relation_type'], unique=False)
    op.create_index(op.f('ix_heritage_site_relations_source_site_id'), 'heritage_site_relations', ['source_site_id'], unique=False)
    op.create_index(op.f('ix_heritage_site_relations_target_site_id'), 'heritage_site_relations', ['target_site_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_heritage_site_relations_target_site_id'), table_name='heritage_site_relations')
    op.drop_index(op.f('ix_heritage_site_relations_source_site_id'), table_name='heritage_site_relations')
    op.drop_index(op.f('ix_heritage_site_relations_relation_type'), table_name='heritage_site_relations')
    op.drop_table('heritage_site_relations')
    # ### end Alembic commands ###
