"""create AI knowledge tables

Revision ID: f515ceb60c1f
Revises: 0e39da2af598
Create Date: 2026-08-14 20:52:02.380501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f515ceb60c1f'
down_revision: Union[str, Sequence[str], None] = '0e39da2af598'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_knowledge_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('document_type', sa.Enum('SITE_PROFILE', 'HISTORICAL_EVENT', 'RELATIONSHIP', 'MEDIA_CONTEXT', name='aiknowledgedocumenttype'), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.Column('provenance_level', sa.String(length=50), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['heritage_sites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['heritage_site_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_knowledge_documents_document_type'), 'ai_knowledge_documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_ai_knowledge_documents_language'), 'ai_knowledge_documents', ['language'], unique=False)
    op.create_index(op.f('ix_ai_knowledge_documents_provenance_level'), 'ai_knowledge_documents', ['provenance_level'], unique=False)
    op.create_index(op.f('ix_ai_knowledge_documents_site_id'), 'ai_knowledge_documents', ['site_id'], unique=False)
    op.create_index(op.f('ix_ai_knowledge_documents_source_id'), 'ai_knowledge_documents', ['source_id'], unique=False)
    op.create_table('ai_knowledge_chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['ai_knowledge_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_knowledge_chunks_document_id'), 'ai_knowledge_chunks', ['document_id'], unique=False)
    op.create_table('ai_embeddings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('chunk_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('dimensions', sa.Integer(), nullable=False),
    sa.Column('vector_index_key', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['ai_knowledge_chunks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_embeddings_chunk_id'), 'ai_embeddings', ['chunk_id'], unique=True)
    op.create_index(op.f('ix_ai_embeddings_model'), 'ai_embeddings', ['model'], unique=False)
    op.create_index(op.f('ix_ai_embeddings_provider'), 'ai_embeddings', ['provider'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_embeddings_provider'), table_name='ai_embeddings')
    op.drop_index(op.f('ix_ai_embeddings_model'), table_name='ai_embeddings')
    op.drop_index(op.f('ix_ai_embeddings_chunk_id'), table_name='ai_embeddings')
    op.drop_table('ai_embeddings')
    op.drop_index(op.f('ix_ai_knowledge_chunks_document_id'), table_name='ai_knowledge_chunks')
    op.drop_table('ai_knowledge_chunks')
    op.drop_index(op.f('ix_ai_knowledge_documents_source_id'), table_name='ai_knowledge_documents')
    op.drop_index(op.f('ix_ai_knowledge_documents_site_id'), table_name='ai_knowledge_documents')
    op.drop_index(op.f('ix_ai_knowledge_documents_provenance_level'), table_name='ai_knowledge_documents')
    op.drop_index(op.f('ix_ai_knowledge_documents_language'), table_name='ai_knowledge_documents')
    op.drop_index(op.f('ix_ai_knowledge_documents_document_type'), table_name='ai_knowledge_documents')
    op.drop_table('ai_knowledge_documents')
    # ### end Alembic commands ###
